version: "3.9"

services:
  backend:
    build: .
    container_name: genai-backend

    ports:
      - "8000:8000"

    volumes:
      - ./data:/app/data
      - ./memory_store:/app/memory_store

    environment:
      GROQ_API_KEY: ${GROQ_API_KEY}

    restart: unless-stopped
